$APP_NAME = "SignSSH"
$INSTALL_EXE = "signssh.exe"
$LOCAL_AMD64 = "signssh-windows-amd64\signssh.exe"
$LOCAL_ARM64 = "signssh-windows-arm64\signssh.exe"
$INSTALL_DIR = "Join-Path `$env:ProgramFiles 'DLNTools'"
$SOURCE_AMD64 = Join-Path $PSScriptRoot $LOCAL_AMD64
$SOURCE_ARM64 = Join-Path $PSScriptRoot $LOCAL_ARM64

# Compute the SHA256 hashes of the local files
$HASH_AMD64 = (Get-FileHash -LiteralPath $SOURCE_AMD64 -Algorithm SHA256).Hash
$HASH_ARM64 = (Get-FileHash -LiteralPath $SOURCE_ARM64 -Algorithm SHA256).Hash

# Output the hashes for reference
Write-Output "AMD64 SHA256: $HASH_AMD64"
Write-Output "ARM64 SHA256: $HASH_ARM64"

$SCRIPT_DEPLOY = @"
# AUTOGENERATED FILE - DO NOT EDIT
param(
    [Parameter(Mandatory)]
    [ValidateSet('Install', 'Uninstall')]
    [string]`$Mode
)

`$InstallDirectory = ${INSTALL_DIR}
`$InstalledExe     = Join-Path `$InstallDirectory '${INSTALL_EXE}'
`$Architecture     = `$env:PROCESSOR_ARCHITEW6432
if (-not `$Architecture) {
    `$Architecture = `$env:PROCESSOR_ARCHITECTURE
}

`$SourceExe        = switch ("`${Architecture}".ToUpper()) {
    'AMD64' {
        Join-Path `$PSScriptRoot 'prog-amd64.exe'
    }

    'ARM64' {
        Join-Path `$PSScriptRoot 'prog-arm64.exe'
    }

    default {
        throw "Unsupported architecture: `$Architecture"
    }
}

function Update-MachinePath {
    param(
        [Parameter(Mandatory)]
        [ValidateSet('Add', 'Remove')]
        [string]`$Action
    )

    `$MachinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    `$Entries = @(
        `$MachinePath -split ';' |
        Where-Object { -not [string]::IsNullOrWhiteSpace(`$_) }
    )

    `$NormalizedInstallDirectory = `$InstallDirectory.TrimEnd('\')

    if (`$Action -eq 'Add') {
        `$AlreadyPresent = `$Entries | Where-Object {
            `$_.Trim().TrimEnd('\') -ieq `$NormalizedInstallDirectory
        }

        if (-not `$AlreadyPresent) {
            `$Entries += `$InstallDirectory
        }
    }
    else {
        `$Entries = @(
            `$Entries | Where-Object {
                `$_.Trim().TrimEnd('\') -ine `$NormalizedInstallDirectory
            }
        )
    }

    [Environment]::SetEnvironmentVariable(
        'Path',
        (`$Entries -join ';'),
        'Machine'
    )
}

try {
    switch (`$Mode) {
        'Install' {
            if (-not (Test-Path -LiteralPath `$SourceExe -PathType Leaf)) {
                throw "Required source file not found: `$SourceExe"
            }

            New-Item ``
                -Path `$InstallDirectory ``
                -ItemType Directory ``
                -Force ``
                -ErrorAction Stop | Out-Null
            Copy-Item ``
                -LiteralPath `$SourceExe ``
                -Destination `$InstalledExe ``
                -Force ``
                -ErrorAction Stop
            
            # Verify the file actually exists after copy
            if (-not (Test-Path -LiteralPath `$InstalledExe -PathType Leaf)) {
                throw "Failed to install executable: `$InstalledExe"
            }

            Update-MachinePath -Action Add
        }

        'Uninstall' {
            # Remove the installed executable if it exists
            if (Test-Path -LiteralPath `$InstalledExe) {
                Remove-Item -LiteralPath `$InstalledExe -Force -ErrorAction SilentlyContinue
            }

            # Remove the install directory only if it is empty
            if (Test-Path -LiteralPath `$InstallDirectory) {
                `$isEmpty = @(Get-ChildItem -LiteralPath `$InstallDirectory ``
                    -Force -ErrorAction SilentlyContinue).Count -eq 0
                if (`$isEmpty) {
                    Remove-Item -LiteralPath `$InstallDirectory -Force -ErrorAction SilentlyContinue

                    # Only update PATH if the directory was successfully removed
                    if (-not (Test-Path -LiteralPath `$InstallDirectory)) {
                        Update-MachinePath -Action Remove
                    }
                }
            }
        }
    }

    exit 0
}
catch {
    Write-Error `$_
    exit 1
}
"@

$SCRIPT_DETECT = @"
# AUTOGENERATED FILE - DO NOT EDIT
`$InstallDirectory = ${INSTALL_DIR}
`$InstalledExe     = Join-Path `$InstallDirectory '${INSTALL_EXE}'

# Replace these with the hashes from Get-FileHash.
`$ExpectedHashes = @{
    AMD64 = '${HASH_AMD64}'
    ARM64 = '${HASH_ARM64}'
}

if (-not (Test-Path -LiteralPath `$InstalledExe -PathType Leaf)) {
    Write-Output "not installed: `$InstalledExe"
    exit 1
}

`$Architecture     = `$env:PROCESSOR_ARCHITEW6432
if (-not `$Architecture) {
    `$Architecture = `$env:PROCESSOR_ARCHITECTURE
}

if (-not `$ExpectedHashes.ContainsKey(`$Architecture)) {
    # This architecture is not supported by this script
    Write-Error "unsupported architecture: `$Architecture"
    exit 1
}

try {
    `$InstalledHash = (Get-FileHash -LiteralPath `$InstalledExe -Algorithm SHA256).Hash
    if (`$InstalledHash -ieq `$ExpectedHashes[`$Architecture]) {
        Write-Output "already installed: `$Architecture, SHA256 `$InstalledHash"
        exit 0
    }
} catch { }

exit 1
"@


$buildDir = Join-Path $PSScriptRoot "build_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
$packageDir = Join-Path $buildDir "package"

if (Test-Path -Path $buildDir -PathType Container) {
    Remove-Item -Path $buildDir -Recurse -Force
}

New-Item -Path $buildDir -ItemType Directory -Force | Out-Null
New-Item -Path $packageDir -ItemType Directory -Force | Out-Null

Copy-Item -LiteralPath $SOURCE_AMD64 -Destination "$packageDir\prog-amd64.exe" -Force -ErrorAction Stop
Copy-Item -LiteralPath $SOURCE_ARM64 -Destination "$packageDir\prog-arm64.exe" -Force -ErrorAction Stop

Set-Content -Path "${packageDir}\${APP_NAME}.ps1" -Encoding UTF8 -Force -Value $SCRIPT_DEPLOY
Set-Content -Path "${buildDir}\detect.ps1" -Encoding UTF8 -Force -Value $SCRIPT_DETECT

$CMD_INSTALL = "%SystemRoot%\Sysnative\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File `".\${APP_NAME}.ps1`" -Mode Install"
Set-Content -Path "${buildDir}\install_command.txt" -Encoding UTF8 -Force -Value $CMD_INSTALL

$CMD_UNINSTALL = "%SystemRoot%\Sysnative\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File `".\${APP_NAME}.ps1`" -Mode Uninstall"
Set-Content -Path "${buildDir}\uninstall_command.txt" -Encoding UTF8 -Force -Value $CMD_UNINSTALL

# "https://raw.githubusercontent.com/microsoft/Microsoft-Win32-Content-Prep-Tool/refs/heads/master/IntuneWinAppUtil.exe"
$ContentPrepTool = Join-Path $PSScriptRoot 'Microsoft-Win32-Content-Prep-Tool\IntuneWinAppUtil.exe'
& $ContentPrepTool `
    -c $packageDir `
    -s "${APP_NAME}.ps1" `
    -o $buildDir `
    -q
if ($LASTEXITCODE -ne 0) {
    throw "IntuneWinAppUtil failed with exit code $LASTEXITCODE."
}